language: node_js
node_js:
- 6.9.1
branches:
  only:
  - develop
install:
- npm i webpack
before_script:
- npm run build
deploy:
  provider: releases
  api_key: $$GH_TOKEN
  file:
  - dist/fun-metis.min.js
  - src/fun-metis.js
  skip_cleanup: true
  on:
    tags: true
env:
  matrix:
    secure: 0W6CSn5jo/eUnRR3HNEtHhJZdpkMMUnsPs2c45/YnZE2MowZFukPdYWPBjpbuZLeKILVsjIKSKoE+fgw3S+ZEWe4hoToJ/x7CbKMEq/PSUQA9Em5Wnz8y8wyOQAZDpMH4vV6loY5GC9YwJWCa2aFRWFSWcqXQUZI/DPx0QSRwJGCgRnU17WAyE9jaHk6QRi565w7bVO8eB5YpEKfUWoQmGjKdeQPud/dgYn/W4GDYtbzaZbBmHeZWi1kRpUZUQtbRJ40yW71/gvrQQY8kYV4EfR8IbA2GIkxtNNTYKzV4OB4STEvTKMdYWWfSSqdSdLxAxJqfiCru284baKgjAYlj2eXtRet2Hxo7dxB8bsaxwG63m36ED0eT8EgS1zx+tfC0BseRGDrsIaAc6hdM/WU26T3FU0kOHAbiKo+8q3HcR+a1b930AVuomXXvs6hXnKCC8VPWGIgQw90DvJZF3cO24a37OjQWggW6D8Ndp5gU1hC79LjG9OqrHRGEhIPyphzyBhHLbHWqiTDegK4w8hjW93lVM20MR9TBbF5IzFJd+1uG3zaT4U4UsFxDHWVJWOi52/lPxb9JV7kvZ1w/yqE1FL9WDQ+vmJY3Q9ip3BOdmjnQFKiFEVaKAb5XzB1jZHoE4y62iY0ZXD6vuD9IoSeXcsY8+lr4xQxhGkX5/lkeUM=
